### ISSUE TITLE
Not work with JDK 8

### ISSUE THREAD

**Issue by greyby** [bodiam/markdown-to-asciidoc#28]
Because [parboiled](https://github.com/sirthias/parboiled)'s bug(sirthias/parboiled#76) before version 1.1.7, [markdown-to-asciidoc](https://github.com/bodiam/markdown-to-asciidoc/) can't work with JDK 8. Please update [pegdown](https://github.com/sirthias/pegdown) to version 1.6.0.

**Comment by bodiam** [comment]
What's the error you're getting? I'm using it in my java 8 problems without any problems.

**Comment by greyby** [comment]
I  got something like this when I'm using [swagger2markup](https://github.com/Swagger2Markup/swagger2markup).
```java
java.lang.RuntimeException: Error creating extended parser class: null
  at org.objectweb.asm.ClassReader.<init>(Unknown Source)
  at org.objectweb.asm.ClassReader.<init>(Unknown Source)
  at org.objectweb.asm.ClassReader.<init>(Unknown Source)
  at org.parboiled.transform.AsmUtils.createClassReader(AsmUtils.java:56)
  at org.parboiled.transform.ClassNodeInitializer.process(ClassNodeInitializer.java:62)
  at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:44)
  at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
  at org.parboiled.Parboiled.createParser(Parboiled.java:54)
```

I made a change of  `build.gradle` and solve that.
```groovy
compile ("io.github.swagger2markup:swagger2markup:1.0.0") { exclude module: "pegdown" }
compile("org.pegdown:pegdown:1.6.0")
```

**Comment by bodiam** [comment]
Pegdown is now updated to version 1.6.0 in 1.1.
